In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import lasio

In [4]:
las = lasio.read("../well-log-data/15_9-13.las")
las

In [6]:
df = las.df()
df.describe()

FORCE_2020_LITHOFACIES_CONFIDENCE  FORCE_2020_LITHOFACIES_LITHOLOGY  \
count                       18277.000000                      18270.000000   
mean                            1.039394                      60476.696223   
std                             0.277921                      13972.748152   
min                             1.000000                      30000.000000   
25%                             1.000000                      65000.000000   
50%                             1.000000                      65000.000000   
75%                             1.000000                      65000.000000   
max                             3.000000                      99000.000000   

               CALI     MUDWEIGHT           ROP          RDEP         RSHA  \
count  18345.000000  17520.000000  20297.000000  20956.000000  1623.000000   
mean      14.766734      0.139824     28.554482      1.934587     2.901504   
std        4.386417      0.009479     30.589891      2.759186     3.474120   
min        8.186605      0.129413      0.138586      0.352202     0.175400   
25%       12.101601      0.133007      5.249922      0.830621     0.934778   
50%       13.896447      0.136602     31.011793      1.386364     1.473143   
75%       18.301279      0.144990     40.664753      2.047000     3.352066   
max       23.329569      0.156973   1083.425415    168.014252    54.536583   

               RMED          RXO            SP           DTC          NPHI  \
count  20957.000000  1627.000000  20956.000000  21282.000000  14105.000000   
mean       1.777486     5.748493     60.649891    132.228668      0.403497   
std        2.739401    71.588789     45.827110     33.646244      0.134053   
min        0.116862     0.171424   -149.232254     55.726753      0.024330   
25%        0.780284     0.934500     31.746324     95.920670      0.314235   
50%        1.230179     1.455721     58.188791    144.200439      0.447975   
75%        1.972084     3.464941     80.050549    153.726254      0.506147   
max      142.606338  2000.000000    153.096802    206.225693      0.800262   

                PEF            GR          RHOB          DRHO      DEPTH_MD  \
count  16446.000000  20900.000000  18345.000000  18345.000000  20956.000000   
mean       3.467550     63.127582      2.113472      0.012935   1691.300000   
std        2.576539     28.701134      0.301098      0.048039    919.542309   
min        1.010027      6.191506      1.404576     -0.679026     98.720001   
25%        2.320927     41.265792      1.964058     -0.007177    895.009979   
50%        2.790998     66.990936      2.055773      0.001629   1691.299988   
75%        4.268998     82.098042      2.388569      0.020609   2487.590027   
max       66.030319    499.022583      2.938594      0.210927   3283.879883   

               X_LOC         Y_LOC         Z_LOC  
count   20956.000000  2.095600e+04  20956.000000  
mean   437628.925584  6.470978e+06  -1666.082887  
std        14.342905  3.677640e+00    919.344110  
min    437592.906250  6.470972e+06  -3257.997803  
25%    437616.375000  6.470975e+06  -2462.194214  
50%    437636.234375  6.470978e+06  -1666.196960  
75%    437640.937500  6.470982e+06   -869.973602  
max    437642.812500  6.470984e+06    -73.719467

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 21441 entries, 25.0 to 3283.88
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   FORCE_2020_LITHOFACIES_CONFIDENCE  18277 non-null  float64
 1   FORCE_2020_LITHOFACIES_LITHOLOGY   18270 non-null  float64
 2   CALI                               18345 non-null  float64
 3   MUDWEIGHT                          17520 non-null  float64
 4   ROP                                20297 non-null  float64
 5   RDEP                               20956 non-null  float64
 6   RSHA                               1623 non-null   float64
 7   RMED                               20957 non-null  float64
 8   RXO                                1627 non-null   float64
 9   SP                                 20956 non-null  float64
 10  DTC                                21282 non-null  float64
 11  NPHI                               14105 non-nu

In [8]:
df.head()

FORCE_2020_LITHOFACIES_CONFIDENCE  FORCE_2020_LITHOFACIES_LITHOLOGY  \
DEPT                                                                          
25.000                                NaN                               NaN   
25.152                                NaN                               NaN   
25.304                                NaN                               NaN   
25.456                                NaN                               NaN   
25.608                                NaN                               NaN   

        CALI  MUDWEIGHT  ROP  RDEP  RSHA  RMED  RXO  SP         DTC  NPHI  \
DEPT                                                                        
25.000   NaN        NaN  NaN   NaN   NaN   NaN  NaN NaN  206.224609   NaN   
25.152   NaN        NaN  NaN   NaN   NaN   NaN  NaN NaN  206.224625   NaN   
25.304   NaN        NaN  NaN   NaN   NaN   NaN  NaN NaN  206.224655   NaN   
25.456   NaN        NaN  NaN   NaN   NaN   NaN  NaN NaN  206.224670   NaN   
25.608   NaN        NaN  NaN   NaN   NaN   NaN  NaN NaN  206.224701   NaN   

        PEF  GR  RHOB  DRHO  DEPTH_MD  X_LOC  Y_LOC  Z_LOC  
DEPT                                                        
25.000  NaN NaN   NaN   NaN       NaN    NaN    NaN    NaN  
25.152  NaN NaN   NaN   NaN       NaN    NaN    NaN    NaN  
25.304  NaN NaN   NaN   NaN       NaN    NaN    NaN    NaN  
25.456  NaN NaN   NaN   NaN       NaN    NaN    NaN    NaN  
25.608  NaN NaN   NaN   NaN       NaN    NaN    NaN    NaN

In [12]:
# with the depth being our initial index, a new index column is created, pushing dept column as the first curve.
df.reset_index(inplace=True)

In [13]:
df.head()

DEPT  FORCE_2020_LITHOFACIES_CONFIDENCE  \
0  25.000                                NaN   
1  25.152                                NaN   
2  25.304                                NaN   
3  25.456                                NaN   
4  25.608                                NaN   

   FORCE_2020_LITHOFACIES_LITHOLOGY  CALI  MUDWEIGHT  ROP  RDEP  RSHA  RMED  \
0                               NaN   NaN        NaN  NaN   NaN   NaN   NaN   
1                               NaN   NaN        NaN  NaN   NaN   NaN   NaN   
2                               NaN   NaN        NaN  NaN   NaN   NaN   NaN   
3                               NaN   NaN        NaN  NaN   NaN   NaN   NaN   
4                               NaN   NaN        NaN  NaN   NaN   NaN   NaN   

   RXO  ...         DTC  NPHI  PEF  GR  RHOB  DRHO  DEPTH_MD  X_LOC  Y_LOC  \
0  NaN  ...  206.224609   NaN  NaN NaN   NaN   NaN       NaN    NaN    NaN   
1  NaN  ...  206.224625   NaN  NaN NaN   NaN   NaN       NaN    NaN    NaN   
2  NaN  ...  206.224655   NaN  NaN NaN   NaN   NaN       NaN    NaN    NaN   
3  NaN  ...  206.224670   NaN  NaN NaN   NaN   NaN       NaN    NaN    NaN   
4  NaN  ...  206.224701   NaN  NaN NaN   NaN   NaN       NaN    NaN    NaN   

   Z_LOC  
0    NaN  
1    NaN  
2    NaN  
3    NaN  
4    NaN  

[5 rows x 21 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21441 entries, 0 to 21440
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   DEPT                               21441 non-null  float64
 1   FORCE_2020_LITHOFACIES_CONFIDENCE  18277 non-null  float64
 2   FORCE_2020_LITHOFACIES_LITHOLOGY   18270 non-null  float64
 3   CALI                               18345 non-null  float64
 4   MUDWEIGHT                          17520 non-null  float64
 5   ROP                                20297 non-null  float64
 6   RDEP                               20956 non-null  float64
 7   RSHA                               1623 non-null   float64
 8   RMED                               20957 non-null  float64
 9   RXO                                1627 non-null   float64
 10  SP                                 20956 non-null  float64
 11  DTC                                21282 non-null  flo

#### Create X (features matrix)

In [24]:
# dropping the target curve
X = df.drop("GR", axis=1)

In [25]:
# drop curves with too little entries
X = X.drop(["RSHA", "RXO"], axis=1)

In [26]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21441 entries, 0 to 21440
Data columns (total 18 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   DEPT                               21441 non-null  float64
 1   FORCE_2020_LITHOFACIES_CONFIDENCE  18277 non-null  float64
 2   FORCE_2020_LITHOFACIES_LITHOLOGY   18270 non-null  float64
 3   CALI                               18345 non-null  float64
 4   MUDWEIGHT                          17520 non-null  float64
 5   ROP                                20297 non-null  float64
 6   RDEP                               20956 non-null  float64
 7   RMED                               20957 non-null  float64
 8   SP                                 20956 non-null  float64
 9   DTC                                21282 non-null  float64
 10  NPHI                               14105 non-null  float64
 11  PEF                                16446 non-null  flo

#### Create y (target)

In [27]:
y = df["GR"]

In [28]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 21441 entries, 0 to 21440
Series name: GR
Non-Null Count  Dtype  
--------------  -----  
20900 non-null  float64
dtypes: float64(1)
memory usage: 167.6 KB


### Option1: Fill missing data with Pandas

In [32]:
# Fill missing data in features curves with mean of respective curve
for curve in X:
    if curve != "DEPT":
        X[curve].fillna(X[curve].mean(), inplace=True)

In [33]:
X.isna().sum()

DEPT                                 0
FORCE_2020_LITHOFACIES_CONFIDENCE    0
FORCE_2020_LITHOFACIES_LITHOLOGY     0
CALI                                 0
MUDWEIGHT                            0
ROP                                  0
RDEP                                 0
RMED                                 0
SP                                   0
DTC                                  0
NPHI                                 0
PEF                                  0
RHOB                                 0
DRHO                                 0
DEPTH_MD                             0
X_LOC                                0
Y_LOC                                0
Z_LOC                                0
dtype: int64

In [35]:
y.fillna(y.mean(), inplace=True)
y.isna().sum()

0

### Build machine learning model
    Following our scikit-learn machine learning map, we have been able to narrow our model to a few Regression model:
   #### RidgeRegression

In [45]:
# Import algorithm/estimator
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

# set up random seed
np.random.seed(42)

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate and fit the model (on the train set)
reg = Ridge()

# fitting
reg.fit(X_train, y_train)

# Score model
reg.score(X_test, y_test)

0.5551476730722198

In [44]:
# train model with 5 different part of the same data
cross_val_score(reg, X, y)

array([-2.98252979e+06,  3.99172474e-01, -2.56146158e+00, -9.68332209e-01,
       -1.33783891e+00])

#### SVR(Support Vector Regression) model

In [46]:
from sklearn.svm import SVR
regr = SVR()
regr.fit(X_train, y_train)
regr.score(X_test, y_test)

-0.010879439075470954

In [47]:
cross_val_score(regr, X, y)

array([-0.02170142, -0.25130754, -0.91775209, -3.52102027, -0.41961983])

#### Linear regression

In [49]:
from sklearn.linear_model import LinearRegression
l_reg = LinearRegression()
l_reg.fit(X_train, y_train)
l_reg.score(X_test, y_test)

0.6027955100093672

In [51]:
cross_val_score(l_reg, X, y)

array([-2.38633425e+08,  2.74595214e-01, -2.85571699e+00, -1.28362006e+00,
       -1.13923688e+00])